"""Added columns to Patient_log table

Revision ID: 0b1da8961e76
Revises: 1bb940f924f7
Create Date: 2025-10-20 12:52:14.366404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1da8961e76'
down_revision = '1bb940f924f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_wait_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.drop_column('estimated_wait_time')

    # ### end Alembic commands ###
