"""Add disease_id to patient_log

Revision ID: 1bb940f924f7
Revises: 7a7ac08fc840
Create Date: 2025-10-17 22:56:55.922734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb940f924f7'
down_revision = '7a7ac08fc840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'disease_desc', ['disease_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('disease_id')

    # ### end Alembic commands ###
