"""Added columns to Patient table

Revision ID: 25baad369c8a
Revises: fbf5daab4e44
Create Date: 2025-09-15 23:32:14.791025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25baad369c8a'
down_revision = 'fbf5daab4e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('next_appointment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('next_appointment_date')
        batch_op.drop_column('treatment_type')

    # ### end Alembic commands ###
