"""Add total_est_time to DoctorLog

Revision ID: 3dd7e53ad5a1
Revises: eeaefd05b139
Create Date: 2025-10-25 22:36:50.791617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd7e53ad5a1'
down_revision = 'eeaefd05b139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_est_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_log', schema=None) as batch_op:
        batch_op.drop_column('total_est_time')

    # ### end Alembic commands ###
