"""Added columns to Patient table

Revision ID: 504271376203
Revises: 965586bf4f9e
Create Date: 2025-08-27 23:39:48.168387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504271376203'
down_revision = '965586bf4f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marital_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('emergency_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('marital_status')

    # ### end Alembic commands ###
