"""Make patient_id nullable in hospital_notifications

Revision ID: 55c3f0e1bcf8
Revises: 4b71c703df9b
Create Date: 2025-10-15 23:26:12.070294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c3f0e1bcf8'
down_revision = '4b71c703df9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_notifications', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
