"""Change the data type of columnns

Revision ID: 673b81dd2825
Revises: 25baad369c8a
Create Date: 2025-09-21 00:15:04.187098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673b81dd2825'
down_revision = '25baad369c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patient_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('patient_nic_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('patient_nic_key'), ['nic'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('patient_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
