"""Added new tables -hospital_notifications/doctor_log/disease_desc 

Revision ID: 6aca0fd3e36b
Revises: 673b81dd2825
Create Date: 2025-09-30 23:56:52.973553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aca0fd3e36b'
down_revision = '673b81dd2825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_desc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('est_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_date', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('updates', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospital_notifications')
    op.drop_table('doctor_log')
    op.drop_table('disease_desc')
    # ### end Alembic commands ###
