"""Added new coloumn to Patient_log table

Revision ID: 795c812230f5
Revises: 3dd7e53ad5a1
Create Date: 2025-10-25 23:25:50.565777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795c812230f5'
down_revision = '3dd7e53ad5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_service_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_est_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.drop_column('total_est_time')
        batch_op.drop_column('estimated_service_time')
        batch_op.drop_column('service_time')

    # ### end Alembic commands ###
