"""Allow nullable patient_log fields

Revision ID: 7a7ac08fc840
Revises: 55c3f0e1bcf8
Create Date: 2025-10-17 22:34:22.326698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7ac08fc840'
down_revision = '55c3f0e1bcf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.alter_column('nurse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nurse_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
