"""Added column to Patient table

Revision ID: 7ad6170f4f13
Revises: 983a7d3afd25
Create Date: 2025-08-28 23:30:41.539367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad6170f4f13'
down_revision = '983a7d3afd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nic', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['nic'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nic')

    # ### end Alembic commands ###
