"""Added medical info columns to Patient

Revision ID: 965586bf4f9e
Revises: 04b65e13b228
Create Date: 2025-08-27 22:57:45.192449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965586bf4f9e'
down_revision = '04b65e13b228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('scan_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('treatment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('treatment_status')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('description')

    op.drop_table('patient_log')
    # ### end Alembic commands ###
