"""Updated emergency contact fields

Revision ID: 983a7d3afd25
Revises: 504271376203
Create Date: 2025-08-27 23:43:19.735566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a7d3afd25'
down_revision = '504271376203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('emergency_contact_first_name')
        batch_op.drop_column('emergency_contact_last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('emergency_contact_name')

    # ### end Alembic commands ###
