"""Changed data type in disease table

Revision ID: 98feeefb5abd
Revises: 6aca0fd3e36b
Create Date: 2025-10-06 00:44:43.669008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98feeefb5abd'
down_revision = '6aca0fd3e36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_desc', schema=None) as batch_op:
        batch_op.alter_column('est_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_desc', schema=None) as batch_op:
        batch_op.alter_column(
            'est_time',
            existing_type=sa.String(length=20),
            type_=sa.INTEGER(),
            nullable=False,
            postgresql_using="est_time::integer"
        )
    # ### end Alembic commands ###
