"""Modify Paitent_log table

Revision ID: d384ab694d5f
Revises: 795c812230f5
Create Date: 2025-11-01 00:19:53.381393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd384ab694d5f'
down_revision = '795c812230f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.drop_column('estimated_service_time')
        batch_op.drop_column('service_time')
        batch_op.drop_column('total_est_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_est_time', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_time', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_service_time', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
