"""Added new coloumn to Doctor_log table

Revision ID: eeaefd05b139
Revises: 0b1da8961e76
Create Date: 2025-10-21 23:36:20.343130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaefd05b139'
down_revision = '0b1da8961e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patients_per_room', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_log', schema=None) as batch_op:
        batch_op.drop_column('patients_per_room')

    # ### end Alembic commands ###
