"""Change est_time from String to Integer

Revision ID: fd3ef947c68d
Revises: d384ab694d5f
Create Date: 2025-11-01 15:46:47.122082
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3ef947c68d'
down_revision = 'd384ab694d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_desc', schema=None) as batch_op:
        batch_op.alter_column(
            'est_time',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using='est_time::integer'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_desc', schema=None) as batch_op:
        batch_op.alter_column(
            'est_time',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True
        )
    # ### end Alembic commands ###
